Add Buck sample.
gojuno/mainframer pull request #103
Opened 2017-01-17 19:38 UTC by artem-zinnatullin

Closes #57.

2017-01-17 19:39 UTC, artem-zinnatullin commented on .travis.yml
> +  - git clone https://github.com/facebook/buck.git
Yeah, there is no built version of buck for Linux/Windows so you have to build it yourself…

2017-01-17 19:41 UTC, arturdryomov requested changes

2017-01-17 19:41 UTC, ming13 commented on .travis.yml
> +  - git clone https://github.com/facebook/buck.git
You are kidding, right? Maybe at least make it a single thing using `&&`?

2017-01-17 19:44 UTC, artem-zinnatullin commented on .travis.yml
> +  - git clone https://github.com/facebook/buck.git
It'll be harder to read, we have comments as dividers.

2017-01-17 19:50 UTC, arturdryomov approved these changes

2017-01-18 09:38 UTC, artem-zinnatullin commented
Nah, later

2017-01-18 09:38 UTC, closed without merging