Refer to samples in options, refine ignore rules.
gojuno/mainframer pull request #116
Opened 2017-01-18 14:49 UTC by artem-zinnatullin

2017-01-19 07:17 UTC, arturdryomov requested changes

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +└── your_project_files
Do not like. `...`

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +* Commit into VCS: no.
`Put to`

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +To speedup execution you might want to **ignore large directories and files** not required for remote command such as `/.git` and so on.
Large directories and files ignoring can speedup sync from and to remote machine.

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +Please see our samples:
Refer to `README.md` section instead. You’ll have to copy this every time from there otherwise.

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +* Commit into VCS: yes.
`Put to`

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +#### `localignore`
No.

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> -### `remoteignore`
No.

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +* Commit into VCS: yes.
Put to.

2017-01-19 07:17 UTC, ming13 commented on docs/OPTIONS.md
> +* Commit into VCS: yes.
Put to.

2017-01-19 07:21 UTC, artem-zinnatullin commented on docs/OPTIONS.md
> +* Commit into VCS: no.
No, nobody says "put into vcs", we **commit** into version control systems.

2017-01-19 07:23 UTC, artem-zinnatullin commented on docs/OPTIONS.md
> +To speedup execution you might want to **ignore large directories and files** not required for remote command such as `/.git` and so on.
What about:

>Ignoring large directories (`/.git`, etc) and files not required for remote command execution can significantly speedup sync process.

2017-01-19 07:24 UTC, artem-zinnatullin commented on docs/OPTIONS.md
> +Please see our samples:
Yup, but that makes documentation 100 times easier for users.

2017-01-19 07:24 UTC, artem-zinnatullin commented on docs/OPTIONS.md
> +* Commit into VCS: yes.
no

2017-01-19 07:24 UTC, artem-zinnatullin commented on docs/OPTIONS.md
> +#### `localignore`
yup, looks beta

2017-01-19 07:49 UTC, ming13 commented on docs/OPTIONS.md
> +To speedup execution you might want to **ignore large directories and files** not required for remote command such as `/.git` and so on.
Without `(/.git, etc)` is fine.

2017-01-19 07:49 UTC, ming13 commented on docs/OPTIONS.md
> +Please see our samples:
Do not agree.

2017-01-19 08:56 UTC, artem-zinnatullin commented on docs/OPTIONS.md
> +To speedup execution you might want to **ignore large directories and files** not required for remote command such as `/.git` and so on.
I don't agree, we need to give some example of commonly used huge directory/file so people will have "aha" moment about `Ignore Rule Files`

2017-01-19 14:32 UTC, artem-zinnatullin commented on docs/OPTIONS.md
> +└── your_project_files
Didn't get it

2017-01-20 07:22 UTC, arturdryomov approved these changes

2017-01-20 10:01 UTC, merged