Rename REMOTE_MACHINE_NAME to REMOTE_MACHINE_ALIAS.
gojuno/mainframer pull request #120
Opened 2017-01-19 15:18 UTC by artem-zinnatullin

2017-01-19 17:25 UTC, arturdryomov requested changes

2017-01-19 17:25 UTC, ming13 commented on docs/SETUP_LOCAL.md
> +* `REMOTE_MACHINE_ALIAS` — ssh alias for remote machine. Something like `blood-dragon` or `sonic`.
`SSH`

2017-01-19 17:25 UTC, ming13 commented on docs/SETUP_LOCAL.md
> +1. Download [latest release version of `mainframer.sh`](https://github.com/gojuno/mainframer/releases/latest) and save it in your project. Most likely commit it into version control system so you cou
commit to VCS

2017-01-19 18:54 UTC, artem-zinnatullin commented on docs/SETUP_LOCAL.md
> +1. Download [latest release version of `mainframer.sh`](https://github.com/gojuno/mainframer/releases/latest) and save it in your project. Most likely commit it into version control system so you cou
NOT EVERYBODY KNOW ACRONYMS YOU

2017-01-20 07:22 UTC, arturdryomov approved these changes

2017-01-20 10:53 UTC, merged