Add "Setup Remote Machine" recipe.
gojuno/mainframer pull request #126
Opened 2017-01-19 19:40 UTC by artem-zinnatullin

Closes #124.

2017-01-20 07:21 UTC, arturdryomov requested changes

2017-01-20 07:21 UTC, ming13 commented on recipes/SETUP_REMOTE_MACHINE.md
> +Bash script that allows easily add new users with ssh keys to the remote machine.
SSH

2017-01-20 07:21 UTC, ming13 commented on recipes/SETUP_REMOTE_MACHINE.md
> +chmod 700 .ssh
Letters please.

2017-01-20 07:40 UTC, artem-zinnatullin commented
Foxed.

2017-01-21 05:35 UTC, arturdryomov requested changes

2017-01-21 05:35 UTC, ming13 commented on docs/SETUP_REMOTE.md
> +## Required Dependencies
Just dependencies.

2017-01-22 13:52 UTC, artem-zinnatullin commented on docs/SETUP_REMOTE.md
> +## Required Dependencies
Why? Let's be more obvious here, no?

2017-01-23 05:53 UTC, arturdryomov requested changes

2017-01-23 05:53 UTC, ming13 commented on docs/SETUP_REMOTE.md
> +## Required Dependencies
We don’t have optional dependencies, so from my point of view it is quite obvious that dependencies are required.

2017-01-23 07:59 UTC, arturdryomov approved these changes

2017-01-23 08:38 UTC, merged