Add tip about auto-download of Android SDK.
gojuno/mainframer pull request #141
Opened 2017-01-27 11:31 UTC by artem-zinnatullin

2017-01-29 19:12 UTC, arturdryomov requested changes

2017-01-29 19:12 UTC, ming13 commented on samples/gradle-android/README.md
> +## Pro Tips
Does not fit the Performance Optimizations section. Also, `Pro` is as lame as new MacBooks (RIP).

```
# Tips
## Auto-download Android SDK
```

2017-01-30 09:13 UTC, artem-zinnatullin commented on samples/gradle-android/README.md
> +## Pro Tips
Foxed, protip is common therm.

2017-01-30 09:34 UTC, ming13 commented
```
# Tips
## Auto-download Android SDK
```

2017-01-30 15:13 UTC, arturdryomov approved these changes

2017-01-30 15:13 UTC, merged