We are now able to specify a custom port for the remote connection
gojuno/mainframer pull request #40
Opened 2016-12-28 18:26 UTC by kokeroulis

It would be nice if we could specify the custom port in which we want to connect using the ssh.
There are some cases that the default port is not available.

2016-12-28 18:31 UTC, artem-zinnatullin commented
You can do this through `~/.ssh/config`

2016-12-28 18:33 UTC, artem-zinnatullin requested changes

2016-12-28 18:33 UTC, artem-zinnatullin commented on mainframer.sh
> +--rsh "ssh -p$REMOTE_SSH_PORT" ./ "$REMOTE_BUILD_MACHINE:~/$PROJECT_DIR_NAME"
Space between `-p` and `$REMOTE_SSH_PORT`?

2016-12-28 18:33 UTC, artem-zinnatullin commented on mainframer.sh
> +--rsh "ssh -p$REMOTE_SSH_PORT" "$REMOTE_BUILD_MACHINE:~/$PROJECT_DIR_NAME/" ./
Same as above

2016-12-28 18:36 UTC, artem-zinnatullin commented
Not sure I'd like to include this since `~/.ssh/config` already allows you specify that and we actually already recommend to create separate config for remote build machine in `~/.ssh/config` to speedify connection so it's already used by most users and doesn't looks like required feature in `mainframer.sh` itself…

@ming13 thoughts?

2016-12-28 18:40 UTC, kokeroulis commented
@artem-zinnatullin i didn't know about ~/.ssh/config, so it looks reasonable to me...

2016-12-28 18:47 UTC, artem-zinnatullin commented
@kokeroulis general rule before spending time on creating pull request — search & create an issue :) 

![i_know_that_feel_bro_by_rober_raik-d4cxn5a](https://cloud.githubusercontent.com/assets/967132/21528953/41d65586-cd47-11e6-815b-c484e3e0e193.png)

2016-12-29 04:41 UTC, ming13 commented
Yep, we should delegate it to the transport itself. As a bonus, you will a get a configured SSH connection, i. e. there will be an ability to SSH to the machine without specifying the port (if I remember it correctly).

2016-12-29 08:42 UTC, artem-zinnatullin commented
Yup. Sorry @kokeroulis, but I'm closing this!

2016-12-29 08:42 UTC, closed without merging

2016-12-29 08:44 UTC, kokeroulis commented
@artem-zinnatullin np!