Add sample for common Gradle project.
gojuno/mainframer pull request #79
Opened 2017-01-09 20:59 UTC by artem-zinnatullin

Closes #18.

2017-01-09 21:00 UTC, artem-zinnatullin commented
Would be great to build samples on CI btw, @ming13?

2017-01-09 21:00 UTC, artem-zinnatullin commented
Actually, lemme try

2017-01-09 21:52 UTC, artem-zinnatullin commented
Lol, it works :) Didn't use `language: java` in `.travis.yml` because it does not support multiple languages, we'll install dependencies for other samples via `apt-get`.

2017-01-10 05:10 UTC, arturdryomov reviewed
Actually you know what, I’m against it. I don’t really see the point. We’ll have `N` projects for `N` build systems and their flavors, store their source code, configure CI, maintain all of this and all for basically nothing. We should not care about such thing if we want to be abstract. Pre-process your Christmas photos on remote machine, if you want to, we don’t care. The real user most likely will try to integrate mainframer directly to its project and for that we will have sample ignore files, this is more than enough.

2017-01-10 07:20 UTC, artem-zinnatullin commented
Well, even though I definitely see the point of what you're talking about and have thought about it for few days before implementing this PR, I've found that without actual project it's pretty hard to write correct ignore rules, I even did a mistake in **this** Gradle sample though we use Gradle for years and `mainframer` with Gradle for more than a month.

Idea is to make samples as easy to use and understand as possible, which means — we better include not only `mainframer` configs but some build system related files (sources, etc).

Btw, most of other build systems would not require us to commit any kind of Gradle wrapper to the repo since most of them don't have such a concept, we'll commit only sources.

2017-01-10 15:46 UTC, arturdryomov requested changes

2017-01-10 15:46 UTC, ming13 commented on samples/gradle/mainframer.sh
> +#!/bin/bash
`dd`

2017-01-10 20:45 UTC, artem-zinnatullin commented
Fixed comment, merging to add other samples

2017-01-10 20:47 UTC, merged