Add rust sample project.
gojuno/mainframer pull request #81
Opened 2017-01-10 22:09 UTC by artem-zinnatullin

Closes #59.

2017-01-11 08:16 UTC, arturdryomov requested changes

2017-01-11 08:16 UTC, arturdryomov commented on .travis.yml
> +  - sudo curl -sf -L https://static.rust-lang.org/rustup.sh | sh
Let’s describe it better. Something like `Dependencies: Rust sample`.

2017-01-12 06:57 UTC, artem-zinnatullin commented on .travis.yml
> +  - sudo curl -sf -L https://static.rust-lang.org/rustup.sh | sh
Foxed

2017-01-12 07:29 UTC, arturdryomov requested changes

2017-01-12 07:29 UTC, ming13 commented on .travis.yml
> +  # Install dependencies for samples projects.
`for sample projects`

2017-01-12 07:29 UTC, ming13 commented on .travis.yml
> +  # JDK for Gradle sample.
`## Gradle`

2017-01-12 07:29 UTC, ming13 commented on .travis.yml
> +  # Rust build tools for Rust sample.
`## Rust`

2017-01-12 08:33 UTC, arturdryomov approved these changes

2017-01-12 08:48 UTC, merged